[workspace]
members = [ "build/nphysics2d", "nphysics_testbed2d", "examples2d",
            "build/nphysics3d", "nphysics_testbed3d", "examples3d" ]

[profile.release]
lto = true
codegen-units = 1

[patch.crates-io]
ncollide2d = { path = "../ncollide-dev/build/ncollide2d" }
ncollide3d = { path = "../ncollide-dev/build/ncollide3d" }
nalgebra = { path = "../nalgebra-dev" }
alga = { path = "../alga/alga" }